import type { Config } from 'tailwindcss';

const config: Config = {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        'brand-yellow': '#FFD02F',
        'brand-yellow-deep': '#E6B800',
        'yellow-light': '#FFF6CC',
        'yellow-dark': '#5C4A00',
        'brand-blue': '#4262FF',
        'blue-pressed': '#2D45C9',
        'brand-coral': '#F16C5F',
        'coral-light': '#FCDED9',
        'coral-dark': '#8A2E26',
        'brand-rose': '#FFCDE4',
        'rose-light': '#FFE4F0',
        'brand-teal': '#5BC4BE',
        'teal-light': '#D4F3F0',
        'moss-dark': '#1F4B47',
        'brand-pink': '#FFD4E5',
        'brand-orange-light': '#FFE5D0',
        canvas: '#FFFFFF',
        surface: '#F5F5F7',
        'surface-soft': '#FAFAFC',
        'surface-yellow': '#FFF8D6',
        'surface-pricing-featured': '#ECE6FE',
        hairline: '#E4E4EB',
        'hairline-soft': '#EDEDF0',
        'hairline-strong': '#C5C5D6',
        'ink-deep': '#050038',
        ink: '#050038',
        charcoal: '#2B2A4C',
        slate: '#4D4D7A',
        steel: '#777789',
        stone: '#9D9DAD',
        muted: '#C5C5D6',
        'on-dark': '#FFFFFF',
        'on-dark-muted': 'rgba(255,255,255,0.7)',
        'success-accent': '#3AC267',
        'brand-red': '#FFD1CF',
        'brand-red-dark': '#D43F3F',
        primary: '#050038',
        'on-primary': '#FFFFFF',
        'footer-bg': '#0F0D2E',
      },
      fontFamily: {
        sans: ['Inter', 'Noto Sans', '-apple-system', 'BlinkMacSystemFont', 'sans-serif'],
      },
      fontSize: {
        'hero-display': ['80px', { lineHeight: '1.05', letterSpacing: '-2px', fontWeight: '500' }],
        'display-lg': ['60px', { lineHeight: '1.10', letterSpacing: '-1.5px', fontWeight: '500' }],
        h1: ['48px', { lineHeight: '1.15', letterSpacing: '-1px', fontWeight: '500' }],
        h2: ['36px', { lineHeight: '1.20', letterSpacing: '-0.5px', fontWeight: '500' }],
        h3: ['28px', { lineHeight: '1.25', fontWeight: '500' }],
        h4: ['22px', { lineHeight: '1.30', fontWeight: '500' }],
        h5: ['18px', { lineHeight: '1.40', fontWeight: '500' }],
        subtitle: ['18px', { lineHeight: '1.50', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '1.50', fontWeight: '400' }],
        'body-sm': ['14px', { lineHeight: '1.50', fontWeight: '400' }],
        caption: ['13px', { lineHeight: '1.40', fontWeight: '400' }],
        'caption-bold': ['13px', { lineHeight: '1.40', fontWeight: '600' }],
        micro: ['12px', { lineHeight: '1.40', fontWeight: '500' }],
        'micro-uppercase': ['11px', { lineHeight: '1.40', letterSpacing: '0.5px', fontWeight: '600' }],
        'button-md': ['14px', { lineHeight: '1.30', fontWeight: '500' }],
        'stat-display': ['64px', { lineHeight: '1.10', letterSpacing: '-1.5px', fontWeight: '500' }],
      },
      borderRadius: {
        xs: '4px',
        sm: '6px',
        md: '8px',
        lg: '12px',
        xl: '16px',
        '2xl': '20px',
        '3xl': '28px',
        feature: '32px',
      },
      boxShadow: {
        'elev-1': 'rgba(5, 0, 56, 0.04) 0px 1px 2px 0px',
        'elev-2': 'rgba(5, 0, 56, 0.06) 0px 4px 12px 0px',
        'elev-3': 'rgba(5, 0, 56, 0.08) 0px 12px 32px -4px',
        'elev-4': 'rgba(5, 0, 56, 0.12) 0px 16px 48px -8px',
      },
    },
  },
  plugins: [],
};

export default config;
